apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kgateway
    repo: https://kgateway.dev/charts
    version: 1.0.0
    releaseName: kgateway
    namespace: kgateway-system
  - name: spire
    repo: https://spiffe.github.io/helm-charts/
    version: 0.23.0
    releaseName: spire
    namespace: spire-system
    valuesInline:
      spire-server:
        enabled: true
      spire-agent:
        enabled: true
      spire-csi-driver:
        enabled: true
      spire-controller-manager:
        enabled: true

resources:
  - cluster-spiffe-id.yaml