apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-backend
  namespace: analytics-tier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-api
  template:
    metadata:
      labels:
        app: analytics-api
        spiffe.io/spire-managed-identity: "true"
    spec:
      serviceAccountName: default
      containers:
        - name: api
          image: workspace-service:v8
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: "unix:///spiffe-workload-api/spire-agent.sock"
          volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true
      volumes:
        - name: spiffe-workload-api
          csi:
            driver: csi.spiffe.io
            readOnly: true