apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - db-init-job.yaml
  - workspace-service.yaml
  - gateway.yaml
  - operator-rbac.yaml
  # - jwt-request-auth.yaml
  # - jwt-authorization-policy.yaml