apiVersion: v1
kind: ServiceAccount
metadata:
  name: workspace-service-sa
  namespace: business-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workspace-crd-role
rules:
  - apiGroups: ["platform.ebpf.io"]
    resources: ["workspaces"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workspace-crd-binding
subjects:
  - kind: ServiceAccount
    name: workspace-service-sa
    namespace: business-app
roleRef:
  kind: ClusterRole
  name: workspace-crd-role
  apiGroup: rbac.authorization.k8s.io